import re

DICE_BASE_URL = "https://www.dice.com"

SKILL_JUNK_RE = re.compile(
    r'(?:usd\s*[\d]|\$\s*[\d,]|\d+\s*/\s*hr|per\s*hour|^w-?2$|^c2c$|corp.{0,4}to.{0,4}corp'
    r'|^on-?site$|^remote$|^hybrid$|create\s*job\s*alert|save\s*job|apply\s*now|sign\s*in'
    r'|log\s*in|register|contract\s*w-?2|contract\s*c2c|^full[\s-]*time$|^part[\s-]*time$'
    r'|^contract(?:or)?$|contract\s*independent|depends\s*on\s*experience|\d+%?\s*travel\s*required)',
    re.IGNORECASE,
)

SEARCH_TERMS = [
    "Actimize Developer",
    "Active Directory",
    "Agronomy Operations",
    "AI/ML Engineer",
    "Anti Money Laundering (AML)",
    "Atlassian Engineer / Jira",
    "Big Data Engineer",
    "Bioinformatics",
    "Bioinformatics for UK",
    "Biotechnology",
    "Biotechnology Internship",
    "Business Analyst",
    "Business Analyst for Canada",
    "Business Intelligence Engineer",
    "Business Intelligence Engineer Internships",
    "Chemical Engineer",
    "CLINICAL DATA ANALYST",
    "Clinical Research Coordinator",
    "Cloud Engineer",
    "Cloud Engineer for Ireland",
    "Computer Science",
    "Computer Science Internship",
    "Construction Management",
    "Credit controller for UK",
    "CRM Sales",
    "CRM Specialist",
    "Cyber security",
    "Cybersecurity for Ireland",
    "Cybersecurity for UK",
    "data",
    "data analyst",
    "Data Analyst",
    "Data Analyst for Canada",
    "Data Analyst for UK",
    "Data Analyst Internship for Ireland",
    "Data Analyst Internships",
    "Database Administration",
    "Data Center Technician",
    "Data Engineer",
    "Data Engineer (citizen/h4ead)",
    "Data Engineer for UK",
    "Data science early grad",
    "Data Science for Germany",
    "Data Scientist",
    "Data scientist,Data engineer",
    "Data Scientist, Machine learning Developer, Data Analyst",
    "Design Verification Engineer",
    "DevOps",
    "DevOps for India",
    "DevOps for Ireland",
    "DevOps for UK",
    "DevOps Internships",
    "Dynamics 365",
    "Electrical Engineer",
    "Electrical Project",
    "Electronic Health Records (EHR)",
    "Embedded software",
    "Embedded Software Engineer",
    "Environmental Health and Safety (EHS)",
    "Epic Analyst",
    "ERP",
    "Financial analyst",
    "Financial analyst for Ireland",
    "Financial Analyst, KYC Analyst, AML",
    "Frontend Engineering",
    "full stack",
    "Full Stack",
    "Game Developer",
    "Game Developer",
    "Generative AI",
    "grc",
    "GRC Analyst",
    "Healthcare Data Analyst",
    "Healthcare data analyst, Health care business analyst,Healthcare data engineer",
    "HR Recruiter",
    "ITSM/ITIL",
    "Java Developer",
    "Java Full Stack",
    "Manufacturing engineer (Mechanical)",
    "Manufacturing engineer (Mechanical) for Canada",
    "Marketing Automation Specialist",
    "Mechanical Engineer",
    "Medical Affairs",
    "Medical Coding",
    "MLOps Engineer",
    ".Net",
    ".Net for Ireland",
    "Netsuite",
    "Network Engineer",
    "Network Security Engineer",
    "Payroll Analyst",
    "Pharmacovigilance",
    "Photography",
    "Product Manager",
    "Project Coordinator for Canada",
    "Project Management for Ireland",
    "Project Management Internship",
    "Project Manager",
    "python developer",
    "QA Automation Engineer",
    "Quality Analyst",
    "Quality Analyst for UK",
    "Quality Assurance Engineer",
    "Quality Engineer",
    "Regulatory Affairs",
    "RTL Design Engineer",
    "Safety Analyst",
    "Sailpoint",
    "Sales executive for UK",
    "Salesforce Developer",
    "Salesforce Developer for UK",
    "SAP",
    "Sap basis and security",
    "SAP FICO",
    "SAP MM",
    "Scrum Master",
    "Scrum Master,Business Analyst",
    "Security Engineer",
    "ServiceNow Developer",
    "software developer",
    "Software Developer",
    "Software Engineer",
    "Software Engineer for Ireland",
    "Software/Hardware Asset Management Analyst",
    "Structural Engineer for Canada",
    "Supply Chain",
    "Supply Chain (citizen/h4ead)",
    "Supply Chain for Ireland",
    "Sustainability analyst for Ireland",
    "Data Scientist",
    "Data scientist,Data engineer",
    "Technical program Management (citizen/h4ead)",
    "Tosca Test Automation Engineer",
    "UX Designer",
    "Workday Analyst",
]
